version: 1.0.0

# dev:
#   resourceName: ibk-secret-id
# uat:
#   resourceName: ibk-secret-id
# prd:
#   resourceName: ibk-secret-id

dev:
  resourceName: APP-Con-devsecops-carlos

uat:
  resourceName: APP-Con-devsecops-carlos-uatt

prd:
  resourceName: APP-Con-devsecops-carlos-prdd